name 'chefdocs'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures chefdocs'
long_description 'Installs/Configures chefdocs'
version '0.1.0'
